site_name: Mathematical Visualization for Unreal Engine
site_url: https://neil3d.github.io
repo_url: https://github.com/neil3d/math_viz
site_author: neilfang
copyright: Copyright &copy; 2022 Neil Fang
theme:
  name: material
  logo: images/favicon.ico
  favicon: images/favicon.ico
  features:
    - toc.integrate
extra:
  homepage: https://neil3d.github.io
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://neil3d.github.io
markdown_extensions:
  - toc:
      permalink: True
  - footnotes
  - tables
plugins:
  - search
  - mkdocs-jupyter:
      execute: False
extra_css:
  - stylesheets/extra.css